package com.roxorgaming.gocd.msteams.jsonapi;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Material extends MaterialRevision {
    @JsonProperty("id")
    private int id;

    // Format: "Pipeline", etc.
    @JsonProperty("type")
    private String type;

    // Format: "zoo" or "git@github.com:foo/bar.git, Branch: master"
    @JsonProperty("description")
    private String description;

    @JsonProperty("fingerprint")
    private String fingerPrint;

    public Material(String type, int id, boolean changed) {
        this.type = type;
        this.id = id;
        super.setChanged(changed);
    }

    public boolean isPipeline() {
        return type.equals("Pipeline");
    }

    // Override hashCode and equals with implementations generated by
    // Eclipse so we can compare MaterialRevision objects.

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + id;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Material other = (Material) obj;
        if (id != other.id)
            return false;
        return true;
    }
}
