package com.roxorgaming.gocd.msteams.jsonapi;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Modification  {

    @JsonProperty("id")
    private int id;

    // Format: "cucumber/102/BuildAndPublish/1" for pipelines, and
    // "2d110a724f3e716f801b6e87d420d7f0c32a208f" for git commits.
    @JsonProperty("revision")
    private String revision;

    @JsonProperty("comment")
    private String comment;

    @JsonProperty("user_name")
    private String userName;

    @JsonProperty("modified_time")
    private String modifiedtime;

    @JsonProperty("email_address")
    private String email;

    /**
     * Return a shortened form of the comment, or null if we have no comment.
     * Designed to reduce git commit messages to just their summary line.
     */
    public String summarizeComment() {
        if (comment == null)
            return null;

        String[] lines = comment.split("\\r?\\n");
        return lines[0];
    }

    // Override hashCode and equals with implementations generated by
    // Eclipse so we can compare MaterialRevision objects.

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + id;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Modification other = (Modification) obj;
        if (id != other.id)
            return false;
        return true;
    }

}
